FROM python:3.13-slim

WORKDIR /test_papernest

RUN apt-get update && \
    apt-get install -y --no-install-recommends pkg-config libmariadb-dev libmariadb-dev-compat gcc build-essential && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY . .

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"] 